"""PostgreSQL custom-dump image inventory must be checked before restore."""

from __future__ import annotations

import hashlib
import io
import json
import subprocess
import tarfile
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import Any, cast

import pytest

from octop.config import DatabaseConfig
from octop.infra.backup import system_archive
from octop.infra.backup.manifest import MANIFEST_VERSION, BackupManifest
from octop.infra.db.pool import DatabasePool
from octop.infra.errors import OctopError
from octop.infra.utils.paths import PathLayout

PROJECT = "01ARZ3NDEKTSV4RRFFQ69G5FAV"
IMAGE_A = "01ARZ3NDEKTSV4RRFFQ69G5FAY"
IMAGE_B = "01ARZ3NDEKTSV4RRFFQ69G5FAZ"
COMMENT = "01ARZ3NDEKTSV4RRFFQ69G5FAX"
IMAGE_DATA = b"imgA"
IMAGE_DIGEST = hashlib.sha256(IMAGE_DATA).hexdigest()


def _copy_sql(image_id: str) -> str:
    return (
        "-- generated by pg_restore\n"
        "COPY public.project_todo_comment_images "
        '(image_id, comment_id, object_key, size_bytes, sha256, media_type, "position", created_at) '
        "FROM stdin;\n"
        f"{image_id}\t{COMMENT}\t{PROJECT}/{image_id}\t4\t{IMAGE_DIGEST}\timage/png\t0\t1\n"
        "\\.\n"
    )


def _fake_pg_restore(monkeypatch: pytest.MonkeyPatch, sql: str) -> list[list[str]]:
    calls: list[list[str]] = []
    monkeypatch.setattr(system_archive, "_require_tool", lambda _name: "pg_restore")

    def write_dump_sql(command: list[str], **_kwargs: object) -> subprocess.CompletedProcess[str]:
        calls.append(command)
        output = Path(command[command.index("--file") + 1])
        output.write_text(sql, encoding="utf-8")
        return subprocess.CompletedProcess(command, 0, "", "")

    monkeypatch.setattr(subprocess, "run", write_dump_sql)
    return calls


def test_pg_dump_copy_inventory_reads_exact_image_metadata(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    calls = _fake_pg_restore(monkeypatch, _copy_sql(IMAGE_A))
    dump = tmp_path / "image.dump"
    dump.write_bytes(b"custom dump fixture")

    actual = system_archive._pg_dump_comment_image_metadata(dump, tmp_path)

    assert actual == {f"{PROJECT}/{IMAGE_A}": (4, IMAGE_DIGEST)}
    assert calls[0][0] == "pg_restore"
    assert "--data-only" in calls[0]
    assert "--table=project_todo_comment_images" in calls[0]
    assert "--dbname" not in calls[0]


@pytest.mark.parametrize(
    "sql",
    [
        "-- pg_restore selected no table data\n",
        _copy_sql(IMAGE_A).replace("sha256, media_type", "digest, media_type"),
        _copy_sql(IMAGE_A).replace(f"{PROJECT}/{IMAGE_A}", "../../secret"),
        _copy_sql(IMAGE_A).replace("\\.\n", ""),
        _copy_sql(IMAGE_A).replace(
            "\\.\n",
            f"{IMAGE_A}\t{COMMENT}\t{PROJECT}/{IMAGE_A}\t4\t{IMAGE_DIGEST}\timage/png\t0\t1\n\\.\n",
        ),
    ],
)
def test_pg_dump_copy_inventory_fails_closed_on_unexpected_data(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, sql: str
) -> None:
    _fake_pg_restore(monkeypatch, sql)
    dump = tmp_path / "image.dump"
    dump.write_bytes(b"custom dump fixture")
    with pytest.raises(OctopError, match="invalid comment image database dump"):
        system_archive._pg_dump_comment_image_metadata(dump, tmp_path)


class _NoLiveDatabase:
    dialect = "postgresql"

    @contextmanager
    def connect(self) -> Iterator[Any]:
        raise AssertionError("archive validation must not query the live database")
        yield  # pragma: no cover

    @contextmanager
    def transaction(self) -> Iterator[Any]:
        raise AssertionError("archive validation must not mutate the live database")
        yield  # pragma: no cover

    def close(self) -> None:
        pass


def test_pg_archive_image_mismatch_is_refused_before_live_restore(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    # The archive index/files describe IMAGE_A, while pg_restore extracts
    # IMAGE_B from the custom database dump. The gate must reject this before
    # any pg_restore --dbname call or live pool access.
    _fake_pg_restore(monkeypatch, _copy_sql(IMAGE_B))
    manifest = BackupManifest(
        manifest_version=MANIFEST_VERSION,
        octop_version="test",
        schema_version=33,
        created_at="test",
        home=str(tmp_path),
        db_file="db/octop.dump",
        database_driver="postgresql",
        database_dump_format="pg_custom",
        includes_chats=True,
        includes_project_todo_comment_images=True,
    )
    index = {
        "version": 1,
        "objects": {f"{PROJECT}/{IMAGE_A}": {"size_bytes": 4, "sha256": IMAGE_DIGEST}},
    }
    archive = tmp_path / "mismatched.tar.gz"
    with tarfile.open(archive, "w:gz") as tf:
        for name, contents in (
            ("manifest.json", manifest.to_json().encode()),
            ("db/octop.dump", b"custom dump fixture"),
            ("project-todo-comment-image-index.json", json.dumps(index).encode()),
            (f"project-todo-comment-images/{PROJECT}/{IMAGE_A}", IMAGE_DATA),
        ):
            info = tarfile.TarInfo(name)
            info.size = len(contents)
            tf.addfile(info, io.BytesIO(contents))

    target = PathLayout(tmp_path / "target")
    target.root.mkdir()
    with pytest.raises(OctopError, match="comment image archive index differs from database"):
        system_archive.restore_system_backup(
            archive,
            paths=target,
            pool=cast(DatabasePool, _NoLiveDatabase()),
            db_config=DatabaseConfig(),
        )


def test_pg_backup_refuses_dump_and_live_image_snapshot_mismatch(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    class _Rows:
        def fetchall(self) -> list[tuple[str, int, str]]:
            return [(f"{PROJECT}/{IMAGE_A}", len(IMAGE_DATA), IMAGE_DIGEST)]

    class _Connection:
        def execute(self, query: str) -> _Rows:
            assert "project_todo_comment_images" in query
            return _Rows()

    class _LivePgPool:
        dialect = "postgresql"

        @contextmanager
        def connect(self) -> Iterator[_Connection]:
            yield _Connection()

        @contextmanager
        def transaction(self) -> Iterator[_Connection]:
            yield _Connection()

        def close(self) -> None:
            pass

    layout = PathLayout(tmp_path / "home")
    source = layout.project_todo_comment_images / PROJECT / IMAGE_A
    source.parent.mkdir(parents=True)
    source.write_bytes(IMAGE_DATA)
    monkeypatch.setattr(system_archive, "_current_version", lambda _pool: 33)

    def fake_dump(_conninfo: str, dest: Path, **_kwargs: object) -> None:
        dest.parent.mkdir(parents=True)
        dest.write_bytes(b"custom dump fixture")

    monkeypatch.setattr(system_archive, "dump_postgres", fake_dump)
    monkeypatch.setattr(
        system_archive,
        "_pg_dump_comment_image_metadata",
        lambda _dump, _scratch: {f"{PROJECT}/{IMAGE_B}": (len(IMAGE_DATA), IMAGE_DIGEST)},
        raising=False,
    )
    archive = tmp_path / "snapshot-mismatch.tar.gz"
    with pytest.raises(OctopError, match="comment image dump differs from database"):
        system_archive.create_system_backup(
            paths=layout,
            agent_rows=[],
            pool=cast(DatabasePool, _LivePgPool()),
            db_config=DatabaseConfig(driver="postgresql"),
            dest=archive,
        )
    assert not archive.exists()
    assert not archive.with_name(archive.name + ".partial").exists()
