-- Schema v21 (PostgreSQL): project task links — PS-05 slice 1 private attribution.
-- One existing Dashboard DM thread belongs to at most one project (UNIQUE
-- thread_id). Deleting the project, the thread, or the owner cascades the
-- link away; detaching a link never deletes the original thread. source is
-- server-derived ('manual' is the only writer in this slice); timestamps are
-- integer Unix seconds, matching project_spaces/project_members.

CREATE TABLE IF NOT EXISTS project_task_links (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES project_spaces(project_id) ON DELETE CASCADE,
  thread_id TEXT NOT NULL UNIQUE REFERENCES threads(thread_id) ON DELETE CASCADE,
  owner_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  source TEXT NOT NULL DEFAULT 'manual',
  created_at INTEGER NOT NULL
);

-- Per-member task listing inside a project; sort keys come from the joined
-- threads row (activity sentinel), so the (project_id, owner_user_id) prefix
-- is the only access path this slice needs.
CREATE INDEX IF NOT EXISTS idx_project_task_links_project_owner
  ON project_task_links(project_id, owner_user_id);

UPDATE _schema_version SET version = 21;
