-- Schema v34 (PostgreSQL): project-owned plan dates, priorities and tags.
-- The migration runner seeds existing projects with the public ULID primitive
-- on this connection, inside the DDL transaction, before the watermark.

CREATE TABLE IF NOT EXISTS project_todo_catalog_state (
  project_id TEXT NOT NULL PRIMARY KEY REFERENCES project_spaces(project_id) ON DELETE CASCADE,
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS project_todo_priorities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  priority_id TEXT NOT NULL UNIQUE,
  project_id TEXT NOT NULL REFERENCES project_spaces(project_id) ON DELETE CASCADE,
  name TEXT NOT NULL CHECK (name = trim(name) AND length(name) BETWEEN 1 AND 40),
  name_key TEXT NOT NULL CHECK (length(name_key) >= 1),
  color TEXT NOT NULL CHECK (color IN ('red', 'orange', 'yellow', 'green', 'blue', 'purple', 'gray')),
  position INTEGER NOT NULL CHECK (position >= 0),
  archived_at INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  UNIQUE (project_id, priority_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_project_todo_priorities_active_name
  ON project_todo_priorities(project_id, name_key) WHERE archived_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_project_todo_priorities_project
  ON project_todo_priorities(project_id, archived_at, position, priority_id);

CREATE TABLE IF NOT EXISTS project_todo_tags (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag_id TEXT NOT NULL UNIQUE,
  project_id TEXT NOT NULL REFERENCES project_spaces(project_id) ON DELETE CASCADE,
  name TEXT NOT NULL CHECK (name = trim(name) AND length(name) BETWEEN 1 AND 40),
  name_key TEXT NOT NULL CHECK (length(name_key) >= 1),
  color TEXT NOT NULL CHECK (color IN ('red', 'orange', 'yellow', 'green', 'blue', 'purple', 'gray')),
  archived_at INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  UNIQUE (project_id, tag_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_project_todo_tags_active_name
  ON project_todo_tags(project_id, name_key) WHERE archived_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_project_todo_tags_project
  ON project_todo_tags(project_id, archived_at, name_key, tag_id);

ALTER TABLE project_todos ADD COLUMN IF NOT EXISTS start_date TEXT;
ALTER TABLE project_todos ADD COLUMN IF NOT EXISTS due_date TEXT;
ALTER TABLE project_todos ADD COLUMN IF NOT EXISTS priority_id TEXT;
ALTER TABLE project_todos ADD CONSTRAINT uq_project_todos_project_todo UNIQUE (project_id, todo_id);
ALTER TABLE project_todos ADD CONSTRAINT fk_project_todos_priority
  FOREIGN KEY (project_id, priority_id)
  REFERENCES project_todo_priorities(project_id, priority_id) ON DELETE NO ACTION;
ALTER TABLE project_todos ADD CONSTRAINT ck_project_todos_start_date CHECK (
  start_date IS NULL OR (
    length(start_date) = 10 AND
    start_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' AND
    start_date BETWEEN '1900-01-01' AND '9999-12-31'
  )
);
ALTER TABLE project_todos ADD CONSTRAINT ck_project_todos_due_date CHECK (
  due_date IS NULL OR (
    length(due_date) = 10 AND
    due_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' AND
    due_date BETWEEN '1900-01-01' AND '9999-12-31'
  )
);
ALTER TABLE project_todos ADD CONSTRAINT ck_project_todos_date_order CHECK (
  start_date IS NULL OR due_date IS NULL OR start_date <= due_date
);

CREATE TABLE IF NOT EXISTS project_todo_tag_links (
  project_id TEXT NOT NULL,
  todo_id TEXT NOT NULL,
  tag_id TEXT NOT NULL,
  PRIMARY KEY (project_id, todo_id, tag_id),
  FOREIGN KEY (project_id, todo_id)
    REFERENCES project_todos(project_id, todo_id) ON DELETE CASCADE,
  FOREIGN KEY (project_id, tag_id)
    REFERENCES project_todo_tags(project_id, tag_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_project_todo_tag_links_tag
  ON project_todo_tag_links(project_id, tag_id, todo_id);

UPDATE _schema_version SET version = 34;
