CREATE TABLE IF NOT EXISTS project_todo_display_state (
  project_id TEXT NOT NULL,
  todo_id TEXT NOT NULL,
  revision BIGINT NOT NULL DEFAULT 1 CHECK (revision BETWEEN 1 AND 9007199254740991),
  updated_at BIGINT NOT NULL CHECK (updated_at >= 0),
  PRIMARY KEY (project_id, todo_id),
  FOREIGN KEY (project_id, todo_id) REFERENCES project_todos(project_id, todo_id) ON DELETE CASCADE
);

-- D1_STATEMENT_BOUNDARY

CREATE TABLE IF NOT EXISTS project_todo_attachment_state (
  project_id TEXT NOT NULL,
  todo_id TEXT NOT NULL,
  revision BIGINT NOT NULL DEFAULT 1 CHECK (revision BETWEEN 1 AND 9223372036854775807),
  updated_at BIGINT NOT NULL CHECK (updated_at >= 0),
  PRIMARY KEY (project_id, todo_id),
  FOREIGN KEY (project_id, todo_id) REFERENCES project_todos(project_id, todo_id) ON DELETE CASCADE
);

-- D1_STATEMENT_BOUNDARY

CREATE TABLE IF NOT EXISTS project_todo_attachment_usage (
  project_id TEXT NOT NULL PRIMARY KEY REFERENCES project_spaces(project_id) ON DELETE CASCADE,
  used_bytes BIGINT NOT NULL DEFAULT 0 CHECK (used_bytes BETWEEN 0 AND 1073741824),
  updated_at BIGINT NOT NULL CHECK (updated_at >= 0)
);

-- D1_STATEMENT_BOUNDARY

CREATE TABLE IF NOT EXISTS project_todo_attachments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attachment_id TEXT NOT NULL UNIQUE CHECK (length(attachment_id) = 26),
  project_id TEXT NOT NULL,
  todo_id TEXT NOT NULL,
  uploader_user_id INTEGER NOT NULL CHECK (uploader_user_id > 0),
  display_name TEXT NOT NULL CHECK (
    length(display_name) BETWEEN 1 AND 120 AND display_name = trim(display_name)
    AND strpos(display_name, '/') = 0 AND strpos(display_name, chr(92)) = 0
    AND length(replace(display_name, '.', '')) > 0
  ),
  size_bytes BIGINT NOT NULL CHECK (size_bytes BETWEEN 0 AND 26214400),
  sha256 TEXT NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
  preview_media_type TEXT CHECK (preview_media_type IN ('image/png', 'image/jpeg', 'image/webp')),
  preview_width INTEGER,
  preview_height INTEGER,
  object_key TEXT NOT NULL UNIQUE CHECK (object_key = project_id || '/' || attachment_id),
  created_at BIGINT NOT NULL CHECK (created_at >= 0),
  removed_at BIGINT CHECK (removed_at IS NULL OR removed_at >= created_at),
  client_request_id TEXT NOT NULL
    CHECK (client_request_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
  request_fingerprint TEXT NOT NULL CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
  FOREIGN KEY (project_id, todo_id) REFERENCES project_todos(project_id, todo_id) ON DELETE CASCADE,
  UNIQUE (project_id, todo_id, uploader_user_id, client_request_id),
  CHECK (
    (preview_media_type IS NULL AND preview_width IS NULL AND preview_height IS NULL)
    OR (preview_media_type IS NOT NULL AND preview_width IS NOT NULL AND preview_height IS NOT NULL
      AND preview_width BETWEEN 1 AND 40000000 AND preview_height BETWEEN 1 AND 40000000
      AND preview_width::BIGINT * preview_height::BIGINT <= 40000000
      AND size_bytes BETWEEN 1 AND 8388608)
  )
);

-- D1_STATEMENT_BOUNDARY

CREATE TABLE IF NOT EXISTS project_todo_attachment_retained_objects (
  object_key TEXT NOT NULL PRIMARY KEY,
  attachment_id TEXT NOT NULL UNIQUE CHECK (length(attachment_id) = 26),
  project_id TEXT NOT NULL,
  todo_id TEXT NOT NULL,
  uploader_user_id INTEGER NOT NULL CHECK (uploader_user_id > 0),
  display_name TEXT NOT NULL CHECK (
    length(display_name) BETWEEN 1 AND 120 AND display_name = trim(display_name)
    AND strpos(display_name, '/') = 0 AND strpos(display_name, chr(92)) = 0
    AND length(replace(display_name, '.', '')) > 0
  ),
  size_bytes BIGINT NOT NULL CHECK (size_bytes BETWEEN 0 AND 26214400),
  sha256 TEXT NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
  preview_media_type TEXT CHECK (preview_media_type IN ('image/png', 'image/jpeg', 'image/webp')),
  preview_width INTEGER,
  preview_height INTEGER,
  created_at BIGINT NOT NULL CHECK (created_at >= 0),
  removed_at BIGINT CHECK (removed_at IS NULL OR removed_at >= created_at),
  client_request_id TEXT NOT NULL
    CHECK (client_request_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
  request_fingerprint TEXT NOT NULL CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
  retained_at BIGINT NOT NULL CHECK (retained_at >= 0),
  CHECK (object_key = project_id || '/' || attachment_id),
  CHECK (
    (preview_media_type IS NULL AND preview_width IS NULL AND preview_height IS NULL)
    OR (preview_media_type IS NOT NULL AND preview_width IS NOT NULL AND preview_height IS NOT NULL
      AND preview_width BETWEEN 1 AND 40000000 AND preview_height BETWEEN 1 AND 40000000
      AND preview_width::BIGINT * preview_height::BIGINT <= 40000000
      AND size_bytes BETWEEN 1 AND 8388608)
  )
);

-- D1_STATEMENT_BOUNDARY

CREATE INDEX IF NOT EXISTS idx_project_todo_attachments_active
  ON project_todo_attachments(project_id, todo_id, created_at, attachment_id) WHERE removed_at IS NULL;

-- D1_STATEMENT_BOUNDARY

CREATE INDEX IF NOT EXISTS idx_project_todo_attachments_removed
  ON project_todo_attachments(project_id, todo_id, removed_at, attachment_id) WHERE removed_at IS NOT NULL;

-- D1_STATEMENT_BOUNDARY

CREATE INDEX IF NOT EXISTS idx_project_todo_attachment_retained_project
  ON project_todo_attachment_retained_objects(project_id, object_key);

-- D1_STATEMENT_BOUNDARY

CREATE INDEX IF NOT EXISTS idx_project_todos_assignee_display_delete
  ON project_todos(assignee_user_id, project_id, todo_id);

-- D1_STATEMENT_BOUNDARY

CREATE INDEX IF NOT EXISTS idx_project_todos_creator_attachment_delete
  ON project_todos(creator_user_id, project_id, todo_id);

-- D1_STATEMENT_BOUNDARY

CREATE OR REPLACE FUNCTION project_todo_attachment_retain_before_delete()
RETURNS trigger LANGUAGE plpgsql AS $d1$
BEGIN
  IF EXISTS (
    SELECT 1 FROM project_todo_attachment_retained_objects r WHERE r.object_key = OLD.object_key
      AND ROW(r.attachment_id, r.project_id, r.todo_id, r.uploader_user_id, r.display_name,
        r.size_bytes, r.sha256, r.preview_media_type, r.preview_width, r.preview_height,
        r.created_at, r.removed_at, r.client_request_id, r.request_fingerprint)
      IS DISTINCT FROM ROW(OLD.attachment_id, OLD.project_id, OLD.todo_id,
        OLD.uploader_user_id, OLD.display_name, OLD.size_bytes, OLD.sha256,
        OLD.preview_media_type, OLD.preview_width, OLD.preview_height,
        OLD.created_at, OLD.removed_at, OLD.client_request_id, OLD.request_fingerprint)
  ) THEN
    RAISE EXCEPTION 'todo_attachment_retained_conflict' USING ERRCODE = '23514';
  END IF;
  INSERT INTO project_todo_attachment_retained_objects (
    object_key, attachment_id, project_id, todo_id, uploader_user_id, display_name,
    size_bytes, sha256, preview_media_type, preview_width, preview_height,
    created_at, removed_at, client_request_id, request_fingerprint, retained_at
  ) VALUES (
    OLD.object_key, OLD.attachment_id, OLD.project_id, OLD.todo_id, OLD.uploader_user_id, OLD.display_name,
    OLD.size_bytes, OLD.sha256, OLD.preview_media_type, OLD.preview_width, OLD.preview_height,
    OLD.created_at, OLD.removed_at, OLD.client_request_id, OLD.request_fingerprint,
    floor(extract(epoch FROM statement_timestamp()))::BIGINT
  ) ON CONFLICT(object_key) DO NOTHING;
  RETURN OLD;
END;
$d1$;

-- D1_STATEMENT_BOUNDARY

CREATE TRIGGER trg_project_todo_attachment_retain_before_delete
BEFORE DELETE ON project_todo_attachments
FOR EACH ROW EXECUTE FUNCTION project_todo_attachment_retain_before_delete();

-- D1_STATEMENT_BOUNDARY

CREATE OR REPLACE FUNCTION users_todo_display_before_delete()
RETURNS trigger LANGUAGE plpgsql AS $d1$
DECLARE
  target record;
  changed INTEGER;
BEGIN
  FOR target IN
    SELECT t.project_id, t.todo_id FROM project_todos t
    WHERE t.assignee_user_id = OLD.id AND t.creator_user_id <> OLD.id
    ORDER BY t.project_id, t.todo_id FOR UPDATE OF t
  LOOP
    UPDATE project_todo_display_state
      SET revision = revision + 1,
          updated_at = floor(extract(epoch FROM statement_timestamp()))::BIGINT
      WHERE project_id = target.project_id AND todo_id = target.todo_id
        AND revision < 9007199254740991;
    GET DIAGNOSTICS changed = ROW_COUNT;
    IF changed <> 1 THEN
      RAISE EXCEPTION 'todo_display_state_missing_or_exhausted' USING ERRCODE = '23514';
    END IF;
  END LOOP;
  RETURN OLD;
END;
$d1$;

-- D1_STATEMENT_BOUNDARY

CREATE TRIGGER trg_users_todo_display_before_delete
BEFORE DELETE ON users
FOR EACH ROW EXECUTE FUNCTION users_todo_display_before_delete();

-- D1_STATEMENT_BOUNDARY

INSERT INTO project_todo_display_state(project_id, todo_id, revision, updated_at)
SELECT project_id, todo_id, 1, floor(extract(epoch FROM transaction_timestamp()))::BIGINT FROM project_todos
ON CONFLICT(project_id, todo_id) DO NOTHING;

-- D1_STATEMENT_BOUNDARY

INSERT INTO project_todo_attachment_state(project_id, todo_id, revision, updated_at)
SELECT project_id, todo_id, 1, floor(extract(epoch FROM transaction_timestamp()))::BIGINT FROM project_todos
ON CONFLICT(project_id, todo_id) DO NOTHING;

-- D1_STATEMENT_BOUNDARY

INSERT INTO project_todo_attachment_usage(project_id, used_bytes, updated_at)
SELECT project_id, 0, floor(extract(epoch FROM transaction_timestamp()))::BIGINT FROM project_spaces
ON CONFLICT(project_id) DO NOTHING;

-- D1_STATEMENT_BOUNDARY

UPDATE _schema_version SET version = CASE WHEN version < 37 THEN 37 ELSE version END;
