ALTER TABLE project_spaces ADD COLUMN public_connectors_revision BIGINT NOT NULL DEFAULT 1 CHECK(public_connectors_revision BETWEEN 1 AND 9007199254740991);
CREATE TABLE project_public_connector_ids (
  connector_id TEXT PRIMARY KEY NOT NULL CHECK(length(connector_id) > 0),
  reserved_at BIGINT NOT NULL CHECK(reserved_at >= 0)
);
CREATE TABLE project_public_connector_key_state (
  id INTEGER PRIMARY KEY CHECK(id = 1),
  purpose TEXT NOT NULL CHECK(purpose = 'octop.project_public_connector.credentials.v1'),
  initialized INTEGER NOT NULL DEFAULT 0 CHECK(initialized IN (0,1))
);
CREATE TABLE project_public_connectors (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connector_id TEXT NOT NULL UNIQUE REFERENCES project_public_connector_ids(connector_id) ON DELETE RESTRICT,
  project_id TEXT NOT NULL REFERENCES project_spaces(project_id) ON DELETE CASCADE,
  kind TEXT NOT NULL CHECK(kind = 'http_mcp_static_bearer'),
  display_name TEXT NOT NULL CHECK(length(display_name) BETWEEN 1 AND 64),
  description TEXT NOT NULL DEFAULT '' CHECK(length(description) <= 256),
  state TEXT NOT NULL CHECK(state IN ('active','revoked')),
  grant_revision BIGINT NOT NULL CHECK(grant_revision BETWEEN 1 AND 9007199254740991),
  credential_blob BYTEA,
  key_ref TEXT,
  creator_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  updated_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  revoked_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at BIGINT NOT NULL CHECK(created_at >= 0),
  updated_at BIGINT NOT NULL CHECK(updated_at >= created_at),
  revoked_at BIGINT CHECK(revoked_at >= created_at),
  CHECK((state = 'active' AND credential_blob IS NOT NULL AND octet_length(credential_blob) BETWEEN 1 AND 32768 AND key_ref = 'project_public_connectors_fernet_v1' AND key_ref IS NOT NULL AND revoked_at IS NULL AND revoked_by IS NULL) OR (state = 'revoked' AND credential_blob IS NULL AND key_ref IS NULL AND revoked_at IS NOT NULL))
);
CREATE INDEX idx_project_public_connectors_project ON project_public_connectors(project_id,connector_id);
INSERT INTO project_public_connector_key_state(id,purpose,initialized) VALUES(1,'octop.project_public_connector.credentials.v1',0);
UPDATE _schema_version SET version = CASE WHEN version < 39 THEN 39 ELSE version END;
